services:
  mysql:
    image: mysql:8.0
    container_name: insider-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: insider_db
      MYSQL_USER: insider_user
      MYSQL_PASSWORD: insider_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  
  redis:
    image: redis:alpine
    container_name: insider_redis
    restart: always
    ports:
      - "6379:6379"
      
  adminer:
    image: adminer:latest
    container_name: insider_adminer
    restart: always
    ports:
      - "8080:8080"


volumes:
  db_data: